[workspace]
members = [
    "bin/artemis",
    "bin/cli",
    "bin/ingestor_test",
    "crates/artemis-core",
    "crates/generator",
    "crates/strategies/*",
    "crates/clients/*", 
    "examples/*",
]

default-members = ["bin/artemis", "bin/cli", "bin/ingestor_test"]

[workspace.dependencies]
## stellar
ingest = "^0.0.3"
stellar-xdr = { version = "20.0.0-rc1", features = ["std", "curr", "next", "base64", "serde"] }
soroban-client = "0.1.9"


## eth
ethers = { version = "2", features = ["ws", "rustls"]}
ethers-signers = "2.0"


[profile.release]
panic = 'abort'

[profile.dev]
panic = 'abort'

